# Generated by Django 4.0.6 on 2022-08-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=48, null=True)),
                ('email', models.EmailField(max_length=32, null=True, unique=True)),
                ('referral_route', models.CharField(blank=True, choices=[('other', 'other'), ('friends', 'friends'), ('social', 'social'), ('search', 'search')], max_length=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('media_url', models.URLField()),
                ('store', models.CharField(blank=True, choices=[('manomano', 'manomano'), ('asos', 'asos'), ('darty', 'darty'), ('cdiscount', 'cdiscount'), ('zalando', 'zalando')], max_length=12, null=True)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_discount', models.IntegerField(blank=True, null=True)),
                ('user_notified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('app_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.appuser')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
