# Generated by Django 4.0.6 on 2023-01-15 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=48, null=True, verbose_name='full name')),
                ('email', models.EmailField(max_length=48, null=True, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('referral_route', models.CharField(blank=True, choices=[('friends', 'friends'), ('other', 'other'), ('social', 'social'), ('search', 'search')], max_length=12, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('media_url', models.URLField(blank=True)),
                ('store', models.CharField(blank=True, choices=[('zalando', 'zalando'), ('asos', 'asos')], max_length=12, null=True)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('target_discount', models.IntegerField(blank=True, null=True)),
                ('user_notified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('app_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
