# Generated by Django 4.0.6 on 2022-08-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='referral_route',
            field=models.CharField(blank=True, choices=[('search', 'search'), ('other', 'other'), ('friends', 'friends'), ('social', 'social')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditems',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='trackeditems',
            name='store',
            field=models.CharField(blank=True, choices=[('zalando', 'zalando'), ('manomano', 'manomano'), ('darty', 'darty'), ('asos', 'asos'), ('cdiscount', 'cdiscount')], max_length=12, null=True),
        ),
    ]
