# Generated by Django 4.0.6 on 2023-01-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_appuser_referral_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='referral_route',
            field=models.CharField(blank=True, choices=[('search', 'search'), ('social', 'social'), ('other', 'other'), ('friends', 'friends')], max_length=12, null=True),
        ),
    ]
