# Generated by Django 4.0.6 on 2022-08-13 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_appuser_referral_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='referral_route',
            field=models.CharField(blank=True, choices=[('search', 'search'), ('friends', 'friends'), ('social', 'social'), ('other', 'other')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditems',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.appuser'),
        ),
        migrations.AlterField(
            model_name='trackeditems',
            name='store',
            field=models.CharField(blank=True, choices=[('darty', 'darty'), ('asos', 'asos'), ('zalando', 'zalando'), ('cdiscount', 'cdiscount'), ('manomano', 'manomano')], max_length=12, null=True),
        ),
    ]
