# Generated by Django 4.0.6 on 2022-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_appuser_referral_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='referral_route',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('social', 'social'), ('friends', 'friends'), ('search', 'search')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditems',
            name='store',
            field=models.CharField(blank=True, choices=[('manomano', 'manomano'), ('zalando', 'zalando'), ('darty', 'darty'), ('cdiscount', 'cdiscount'), ('asos', 'asos')], max_length=12, null=True),
        ),
    ]
