# Generated by Django 4.0.6 on 2022-08-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_appuser_referral_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('media_url', models.URLField(blank=True)),
                ('store', models.CharField(blank=True, choices=[('zalando', 'zalando'), ('asos', 'asos'), ('cdiscount', 'cdiscount'), ('darty', 'darty'), ('manomano', 'manomano')], max_length=12, null=True)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_discount', models.IntegerField(blank=True, null=True)),
                ('user_notified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='appuser',
            name='referral_route',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('search', 'search'), ('social', 'social'), ('friends', 'friends')], max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='TrackedItems',
        ),
        migrations.AddField(
            model_name='trackeditem',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.appuser'),
        ),
    ]
