# Generated by Django 4.0.6 on 2022-08-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_trackeditem_alter_appuser_referral_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='referral_route',
            field=models.CharField(blank=True, choices=[('search', 'search'), ('other', 'other'), ('friends', 'friends'), ('social', 'social')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='store',
            field=models.CharField(blank=True, choices=[('asos', 'asos'), ('zalando', 'zalando')], max_length=12, null=True),
        ),
    ]
