# Generated by Django 4.0.6 on 2022-09-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_appuser_referral_route_alter_trackeditem_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='referral_route',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('friends', 'friends'), ('social', 'social'), ('search', 'search')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='store',
            field=models.CharField(blank=True, choices=[('zalando', 'zalando'), ('asos', 'asos')], max_length=12, null=True),
        ),
    ]
